POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "George",
    "number": "002-123-09876"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "002-123-1111"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{

}
